version : "3.8"
services:
  apimongo:
    image: mongo:latest
    container_name: apimongo
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
      - DB_NAME=apiboot
      - DB_USER=apibootuser
      - DB_PASSWORD=apibootpass
#  mongo-express:
#    image: mongo-express
#    container_name: mongo-express
#    ports:
#      - 8081:8081
#    restart: always
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
#      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  data : {}
networks:
  default:
    name: mongodb_network


# docker run -d -p 27017:27017 --name apimongo mongo:latest
# or simply come to this directory and then execute below: compose
# docker-compose up